# Import Libraries

In [64]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics import classification_report, confusion_matrix
from joblib import dump

# Load Dataset

In [2]:
df = pd.read_csv(r"C:\Dataset for practice\spam.csv", encoding='latin-1')

In [3]:
df.head()

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN

# Drop Unwanted Columns

In [4]:
df.drop(columns=['Unnamed: 2','Unnamed: 3','Unnamed: 4'], inplace=True)

In [5]:
df.head(3)

     v1                                                 v2
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...

# Rename Columns Name

In [6]:
df.rename(columns={'v1':'Target', "v2":"Text"}, inplace=True)

In [7]:
df.head(2)

  Target                                               Text
0    ham  Go until jurong point, crazy.. Available only ...
1    ham                      Ok lar... Joking wif u oni...

# Removing Duplicates Data

In [8]:
df.duplicated().sum()

np.int64(403)

In [9]:
df.shape

(5572, 2)

In [10]:
df.drop_duplicates(inplace = True)

In [11]:
df.shape

(5169, 2)

# Feature and Target Selection

In [14]:
x = df['Text']
y = df['Target']

# Train Test Split

In [15]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [16]:
x_train.shape

(4135,)

# CountVectorizer Section

In [17]:
cv = CountVectorizer(stop_words = 'english')

x_train_cv = cv.fit_transform(x_train)
x_test_cv = cv.transform(x_test)

In [18]:
x_test_cv.shape

(1034, 7395)

# Naive Bayes Model

In [19]:
model = MultinomialNB()
model.fit(x_train_cv, y_train)

MultinomialNB()

# Prediction

In [20]:
y_pred = model.predict(x_test_cv)

# Evaluation

In [45]:
print("Classification Report:\n",classification_report(y_test, y_pred))

Classification Report:
               precision    recall  f1-score   support

         ham       0.99      1.00      0.99       889
        spam       0.97      0.91      0.94       145

    accuracy                           0.98      1034
   macro avg       0.98      0.95      0.96      1034
weighted avg       0.98      0.98      0.98      1034

In [44]:
print("Confusion Matrix:\n",confusion_matrix(y_test, y_pred))

Confusion Matrix:
 [[885   4]
 [ 13 132]]

# Simple Test

In [48]:
text = cv.transform(['hello sir ! you won 1000 dollar.'])
output = model.predict(text)
print(output)

['spam']

# Custom Test

In [60]:
def prediction(msg):
    input_msg = cv.transform([msg])
    result = model.predict(input_msg)
    return result

msg = ("Hello bro! How are you.")
print("Message:",msg)
print('Prediction:',prediction(msg),'\n')

msg2 = ('you won 1000 dollar.')
print("Message:",msg2)
print('Prediction:',prediction(msg2))

Message: Hello bro! How are you.
Prediction: ['ham']

Message: you won 1000 dollar.
Prediction: ['spam']

# Saving Model

In [66]:
print(dump(model, 'Spam_detector.joblib'))
print(dump(cv, 'Count_Vectorizer.joblib'))

['Spam_detector.joblib']
['Count_Vectorizer.joblib']